### ISSUE TITLE
[Seggest] Disable resizable property of textarea

### ISSUE THREAD

**Issue by ftonato** [HyunmoAhn/Tiny-Timer#11]
Hello,

I suggest to disable resizable property of _textarea_.

[/app/page/timer.scss#L88](https://github.com/HyunmoAhn/Tiny-Timer/blob/ad0272ae91b756965af143dfb9f4daae45b36dec/app/page/timer.scss#L88)
```css
.Comment__input {
  color: inherit;
  align-self: center;
  text-align: center;
  padding: 5px;
  margin: 5px;
  width: 210px;
  
  resize: none;
}
```
